apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"rng"},"name":"rng","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rng"}},"template":{"metadata":{"labels":{"app":"rng"}},"spec":{"containers":[{"image":"dockercoins/rng:v0.1","name":"rng"}]}}}}
  creationTimestamp: "2023-05-20T08:04:33Z"
  generation: 4
  labels:
    app: rng
  name: rng
  namespace: default
  resourceVersion: "54226"
  uid: a676619f-9e17-489e-8a03-ac73bc704839
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rng
    spec:
      containers:
      - image: dockercoins/rng:v0.1
        imagePullPolicy: IfNotPresent
        name: rng
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  observedGeneration: 4
  readyReplicas: 1
  updatedReplicas: 1
