apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: "2023-05-20T18:11:50Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "80592"
  uid: 9cb5eb82-e338-4d6f-91b0-6fc76e120119
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
